Criando tela de editar pedido
digitalcollege-classes/php-merenda pull request #40
Opened 2024-10-08 03:23 UTC by tiagolimar

Foi incluída a tela de editar pedido. 

![image](https://github.com/user-attachments/assets/f719383d-6065-4ed5-a1a3-73d78d7a15d8)

fix #21

2024-10-08 18:42 UTC, mathewvieira requested changes

2024-10-08 18:42 UTC, mathewvieira commented on views/order/edit.php
> +                <div class="input-group input-group-outline mb-3">
- [ ] Sugestão: Para o input dos itens, seria interessante utilizar Bootstrap Tags Input ou um Bootstrap Textarea. 
Para uma abordagem mais completa e complexa: 
1. Utilizar um datalist para escolher o item desejado.
2. Após isso, o label do item selecionado aparece embaixo do datalist
3. e surge um input ao lado desse label onde é possível informar a quantidade.

Justificativa: Caso seja apenas um input normal, pode ser que conforme for necessário adicionar itens, a visualização seja prejudicada. Ex: "ItemA x1, ItemB x5, ItemC, x6, ItemD x1" ou "Item A 1, Item B 2, Item C 5, Item D 6". Lembrando que é apenas uma sugestão.

2024-10-08 18:43 UTC, mathewvieira requested changes

2024-10-08 18:43 UTC, mathewvieira commented on views/order/edit.php
> +                </div>
- [ ] Sugestão: Para o input dos itens, seria interessante utilizar Bootstrap Tags Input ou um Bootstrap Textarea. 
Para uma abordagem mais completa e complexa: 
1. Utilizar um datalist para escolher o item desejado.
2. Após isso, o label do item selecionado aparece embaixo do datalist
3. e surge um input ao lado desse label onde é possível informar a quantidade.

Justificativa: Caso seja apenas um input normal, pode ser que conforme for necessário adicionar itens, a visualização seja prejudicada. Ex: "ItemA x1, ItemB x5, ItemC, x6, ItemD x1" ou "Item A 1, Item B 2, Item C 5, Item D 6". Lembrando que é apenas uma sugestão.

2024-10-15 21:37 UTC, alessandrofeitoza approved these changes

2024-10-15 21:37 UTC, merged