criando mapping para produtos
digitalcollege-classes/php-merenda pull request #41
Opened 2024-10-08 04:07 UTC by tiagolimar

Foi criado o mapping do ORM para a Entidade Product. Também incluí uma importação que estava faltando dentro da Entity Customer.

![image](https://github.com/user-attachments/assets/9d53b435-cd6c-4679-9cfe-11c0f31f8401)

fix #32

2024-10-08 16:58 UTC, jgaguiarm approved these changes

2024-10-08 18:41 UTC, mathewvieira requested changes

2024-10-08 18:41 UTC, mathewvieira commented on src/Entity/Product.php
> +
- [ ] Remover a quebra de linha dupla e manter apenas uma. 

OBS: Seria bom discutirmos sobre a utilização de um code formatter e linter que fossem padrões para o projeto.

2024-10-15 21:38 UTC, alessandrofeitoza approved these changes

2024-10-15 21:38 UTC, merged