feat(criar-crud-clientes-67): Implementa o CRUD da classe Customers
digitalcollege-classes/php-merenda pull request #69
Opened 2024-10-17 11:08 UTC by MarcusGarca

#67

 Implementa o CRUD da classe Customers

2024-10-17 17:55 UTC, mathewvieira requested changes

2024-10-17 17:55 UTC, mathewvieira commented on src/Controller/CustomerController.php
> +        $customer->setPhoto($_POST['photo']); // Define o caminho da foto
- [ ] Seria possível alterar o field photo? Ex: photoLink, photoURL, profileURL, imagePath, imageLink, imageURL...

Justificativa: Nome do campo ficaria mais descritivo.

2024-10-22 18:08 UTC, alessandrofeitoza approved these changes

2024-10-22 21:31 UTC, alessandrofeitoza approved these changes

2024-10-22 21:31 UTC, merged